# Generated by Django 3.2.9 on 2021-12-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=50)),
                ('book_introduction', models.TextField()),
                ('issue_year', models.IntegerField(max_length=4)),
                ('book_file_name', models.CharField(max_length=100)),
                ('add_book_time', models.TimeField()),
            ],
        ),
    ]
