# Generated by Django 3.2.9 on 2022-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=50)),
                ('book_introduction', models.TextField()),
                ('issue_year', models.IntegerField()),
                ('number_of_downloads', models.IntegerField()),
                ('book_file_name', models.CharField(max_length=100)),
                ('add_book_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('views_addbook', '录入书本'), ('views_searchbook', '查找书本'), ('views_downloadbook', '下载书本'), ('views_addusers', '批量导入用户'), ('views_downloadexcel', '下载批量导入用户excel模板')),
            },
        ),
    ]
