# Generated by Django 3.2.9 on 2022-01-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=50)),
                ('book_introduction', models.TextField(max_length=200)),
                ('issue_year', models.CharField(max_length=50)),
                ('number_of_downloads', models.IntegerField()),
                ('book_file_name', models.CharField(max_length=100)),
                ('add_book_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_group', models.CharField(max_length=50)),
                ('views_func', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
