# Generated by Django 3.2.9 on 2021-12-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='issue_year',
            field=models.IntegerField(),
        ),
    ]
