# Generated by Django 3.2.9 on 2021-12-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_books_issue_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='add_book_time',
            field=models.CharField(max_length=100),
        ),
    ]
