# Generated by Django 3.2.9 on 2021-12-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
