# Generated by Django 3.2.9 on 2021-12-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='App1Permission',
        ),
    ]
