# Generated by Django 3.2.9 on 2021-12-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_permission_app1permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App1Permission',
        ),
    ]
